### ISSUE TITLE
missing fastjet header file "AxesDefinition.hh"

### ISSUE THREAD

**Issue by shaojunlu** [iLCSoft/MarlinFastJet#11]
This header file (AxesDefinition.hh) is required by:
https://github.com/iLCSoft/MarlinFastJet/blob/master/include/VLCAxes.h#L3

fastjet release version 3.2.0 was used by ILD.
I have downloaded fastjet release version 3.2.1 and 3.3.1 too from here.
http://www.fastjet.fr/all-releases.html

No "AxesDefinition.hh" is available in either fastjet release.

Do you use a private version of fastjet?
Would you please provide a correct fastjet release version for this "VLCAxes.h"?
Thank you!

**Comment by petricm** [comment]
This has nothing to do with the fastjet version but with fastjetconotrib, and if you enabled Nsubjettiness.

**Comment by petricm** [comment]
Resolved in discussion of #10
