### ISSUE TITLE
Remove support for FastJet 2

### ISSUE THREAD

**Issue by andresailer** [iLCSoft/MarlinFastJet#12]
Any objections to removing the support for FastJet 2 and requiring FastJet 3?

https://github.com/iLCSoft/MarlinFastJet/blob/7a71692e1de71d6a88408db90211649e3b883e13/CMakeLists.txt#L38

I want to use a function that only exists in FastJet3 and would like to avoid having to code around version dependencies.

**Comment by rete** [comment]
We use FastJet version 3.2.* since a long time now. ILCSoft v01-19-01 already uses FastJet 3.2.0. I guess we can remove the support for version 2.

**Comment by andresailer** [comment]
Thanks for the quick response, dropped the support in #13
