### ISSUE TITLE
storeParticlesInJets flag

### ISSUE THREAD

**Issue by yradkhorrami** [iLCSoft/MarlinFastJet#14]
A runtime error occurs when storeParticlesInJets flag is set to true.

 - OS version: SL 6.10
 - Compiler version: GCC 82
 - Package version: CVMFS release
 - ILCSoft release: v02-01
 - Goal: For updating CovMatrix of jets by ErrorFlow, PFOs should be stored in jets. By setting storeParticlesInJets flag to true, runtime error occurs. See log file please:
[storeParticlesInJets_TRUE.log](https://github.com/iLCSoft/MarlinFastJet/files/4761445/storeParticlesInJets_TRUE.log)

**Comment by rete** [comment]
Hi @yradkhorrami . From your log file file, it looks like you forgot to specify the output collection name for reco particles that goes in the jet (recParticleOut):

```
[ MESSAGE "MyFastJetProcessor"] ---- MyFastJetProcessor -  parameters: 
[ MESSAGE "MyFastJetProcessor"] 	Verbosity:  DEBUG
[ MESSAGE "MyFastJetProcessor"] 	algorithm:  ee_kt_algorithm 
[ MESSAGE "MyFastJetProcessor"] 	clusteringMode:  ExclusiveNJets 2 
[ MESSAGE "MyFastJetProcessor"] 	jetOut:  Durham_2Jets
[ MESSAGE "MyFastJetProcessor"] 	recParticleIn:  PandoraPFOsWithoutIsoLep
[ MESSAGE "MyFastJetProcessor"] 	recParticleOut:  
[ MESSAGE "MyFastJetProcessor"] 	recombinationScheme:  E_scheme
[ MESSAGE "MyFastJetProcessor"] 	storeParticlesInJets:  true
```
Please specify a collection name, it should fix your issue.
Close this issue if this fix is right.

**Comment by yradkhorrami** [comment]
> Hi @yradkhorrami . From your log file file, it looks like you forgot to specify the output collection name for reco particles that goes in the jet (recParticleOut):
> 
> ```
> [ MESSAGE "MyFastJetProcessor"] ---- MyFastJetProcessor -  parameters: 
> [ MESSAGE "MyFastJetProcessor"] 	Verbosity:  DEBUG
> [ MESSAGE "MyFastJetProcessor"] 	algorithm:  ee_kt_algorithm 
> [ MESSAGE "MyFastJetProcessor"] 	clusteringMode:  ExclusiveNJets 2 
> [ MESSAGE "MyFastJetProcessor"] 	jetOut:  Durham_2Jets
> [ MESSAGE "MyFastJetProcessor"] 	recParticleIn:  PandoraPFOsWithoutIsoLep
> [ MESSAGE "MyFastJetProcessor"] 	recParticleOut:  
> [ MESSAGE "MyFastJetProcessor"] 	recombinationScheme:  E_scheme
> [ MESSAGE "MyFastJetProcessor"] 	storeParticlesInJets:  true
> ```
> 
> Please specify a collection name, it should fix your issue.
> Close this issue if this fix is right.

Hi @rete . Yes you are right. I specified the output collection name and it is ok now. I thought it is initialized in the processor!
