### ISSUE TITLE
Jet Clusterer with Kt

### ISSUE THREAD

**Issue by SwathiSasikumar** [iLCSoft/MarlinFastJet#15]
https://github.com/iLCSoft/MarlinFastJet/blob/c16b3e0c7b9da485b57f4144afef41c3905a0486/include/FastJetUtil.h#L238

The Jet clustering processor with kt algorithm does work with different clustering modes but with inclusiveIterative mode. I tried using VLC and kt with different modes. Everything else works but the inclusive mode for kt.
Marlin is terminated with this message: 

A runtime error occured - (uncaught exception):
      std::bad_alloc
 Marlin will have to be terminated, sorry.

**Comment by andresailer** [comment]
Hi @SwathiSasikumar 

Could you make your steering file and input file available that reproduces this problem?
Which iLCSoft installation are you using (CVMFS?)

**Comment by SwathiSasikumar** [comment]
Yes I used the latest iLCSoft installation.

**Comment by SwathiSasikumar** [comment]
<processor name="MyKtJetProcessor" type="FastJetProcessor">
		<parameter name="algorithm" type="StringVec">kt_algorithm 0.75</parameter>
		<parameter name="clusteringMode" type="StringVec">InclusiveIterativeNJets 4 10</parameter>
		
		<parameter name="jetOut" type="string" lcioOutType="ReconstructedParticle">JetOutKT </parameter>
		<parameter name="recParticleIn" type="string" lcioInType="ReconstructedParticle"> PandoraPFOs</parameter>
		<parameter name="recombinationScheme" type="string">E_scheme </parameter>
	</processor>

**Comment by SwathiSasikumar** [comment]
<processor name="MyKtJetProcessor" type="FastJetProcessor">
		<parameter name="algorithm" type="StringVec">kt_algorithm 0.75</parameter>
		<parameter name="clusteringMode" type="StringVec">InclusiveIterativeNJets 4 10</parameter>
		
		<parameter name="jetOut" type="string" lcioOutType="ReconstructedParticle">JetOutKT </parameter>
		<parameter name="recParticleIn" type="string" lcioInType="ReconstructedParticle"> PandoraPFOs</parameter>
		<parameter name="recombinationScheme" type="string">E_scheme </parameter>
	</processor>

**Comment by andresailer** [comment]
The full XML file please.

**Comment by andresailer** [comment]
And the slcio file

**Comment by SwathiSasikumar** [comment]
The steering file is under /nfs/dust/ilc/user/swathi/test.xml 
And the slcio file is /pnfs/desy.de/ilc/prod/ilc/mc-2020/ild/dst-merged/250-SetA/2f_hadronic_eL_pR/ILD_l5_o1_v02/v02-02/00015161/000/rv02-02.sv02-02.mILD_l5_o1_v02.E250-SetA.I500010.P2f_z_h.eL.pR.n001.d_dstm_15161_9.slcio

**Comment by andresailer** [comment]
Thanks, but I cannot access the xml file from there, could you just attach it here?
 I can download the slcio file via the grid though.

**Comment by tmadlener** [comment]
XML steering file: [test.xml.txt](https://github.com/iLCSoft/MarlinFastJet/files/7649195/test.xml.txt)
