### ISSUE TITLE
Large memory usage with FastJetProcessor

### ISSUE THREAD

**Issue by GarcaHec** [iLCSoft/MarlinFastJet#20]
Os version: Centos 7.5.1804
Compiler version: g++ (GCC) 8.2.0
Package version: CVMFS Centos7 

Using ILCSoft v02-02-01 (and also in ILCsoft v02-02-03)

Just running the FastJetProcessor with the algorithm: **ee_kt_algorithm** and clustering mode: **ExclusiveYCut 0.002** increases memory usage without limit, monitored it with the top command. For the analysis of large simulations becomes an issue since the memory of my PC gets full, I do not know if large memory usage is expected. I have tracked the issue to the line 140 of FastJetProcessor.cc by commenting it using a local copy of the processor.
https://github.com/iLCSoft/MarlinFastJet/blob/4bee01f859c26b7faee90317947b9d8ee2e5c373/src/FastJetProcessor.cpp#L140

I am using as input files the production located in DIRAC in this path: /ilc/prod/ilc/mc-2020/ild/dst-merged/250-SetA/higgs/ILD_l5_o2_v02/v02-02-01/00015420/000

**Comment by andresailer** [comment]
Thanks for your report.
This line looks suspicious as there is no cleanup, but every clusterJets call makes a new one.
https://github.com/iLCSoft/MarlinFastJet/blob/4bee01f859c26b7faee90317947b9d8ee2e5c373/include/FastJetUtil.h#L494

**Comment by andresailer** [comment]
Hi @GarcaHec ,
Could you try the changes made in https://github.com/iLCSoft/MarlinFastJet/pull/21 locally?
